name: mynew_project
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  lottie: ^3.0.0  # Added for Lottie animation
  video_player: ^2.9.1
  shared_preferences: ^2.2.2
  smooth_page_indicator: ^1.1.0
  timeago: ^3.6.1
  provider: ^6.1.2
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  firebase_core: ^3.0.0
  flutter_native_splash: ^2.3.0
  zego_uikit_prebuilt_call: ^4.13.0
  zego_uikit: ^2.28.12
  zego_express_engine: ^3.20.0
  flutter_callkit_incoming_yoer: ^2.0.4+3
  uuid: ^4.0.0
  cupertino_icons: ^1.0.8
  audioplayers: ^5.2.1  # Kept for sound effect
  flutter_dotenv: ^5.0.2
  http: ^1.4.0 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/videos/
    - assets/flags/
    - assets/sounds/ 
    - assets/ethiopian_dictionary.json
    - assets/lessons.json
    - .env

flutter_native_splash:
  image: assets/images/logo.png
  background_color: "#ffffff"